// uni-app/components/login/index.vue
<template>
	<view class="login-page">
		<view class="login-form">
			<image class="logo" src="https://img.alicdn.com/imgextra/i1/O1CN01i8XGei1UJflU9uYSW_!!6000000002497-2-tps-96-64.png"></image>
			<view class="login-title">阿里云互动直播</view>
			<view class="nick-block">
				<input
					v-model="nickName"
					@focus="() => {inputFocus = true}"
					@blur="() => {inputFocus = false}"
				/>
				<view :class="['nick-tip', { focus: !!nickName || inputFocus }]">昵称（请输入英文字母、数字）</view>
			</view>
			
			<view class="login-btn">
				<primary-button
					:disabled="!nickName"
					:loading="logging"
					@click="login"
				>
					进入
				</primary-button>
			</view>
		</view>
	</view>
</template>

<script>
	import PrimaryButton from '@/components/primaryButton/index.vue';
	import services from '@/utils/services.js';
	
	export default {
		components: {
			PrimaryButton,
		},
		
		data() {
			return {
				nickName: '',
				inputFocus: false,
				logging: false,
			};
		},
		
		methods: {
			login() {
				const userName = this.nickName.trim();
				if (this.logging) {
					return;
				}
				if (!/^[a-zA-Z0-9]+$/.test(userName)) {
					uni.showModal({
						content: '昵称只支持英文字母、数字',
						showCancel: false,
						confirmText: '确定',
						confirmColor: '#FF5722',
					});
					return;
				}
				
				this.logging = true;
				
				services
					.login(userName, userName)
					.then((res) => {
						// 登录成功跳转
						uni.redirectTo({
							url: '/pages/roomList/roomList',
						});
					})
					.catch((err) => {
						console.log('err->', err);
						uni.showToast({
							title: '登录失败',
							icon: 'error',
						});
					})
					.finally(() => {
						this.logging = false;
					});
			},
		}
	};
</script>

<style lang="scss" scoped>
	@import "./index.scss";
</style>

// Web/src/components/login/index.tsx
/**
 * 本组件为测试逻辑，userId 与输入的昵称一样，方便测试
 * 实际生产环境的登录由您自行实现
*/
import { useState, useMemo } from 'react';
import { Toast, Input, Button, Dialog } from 'antd-mobile';
import { useTranslation } from 'react-i18next';
import services from '@/services';
import styles from './index.less';

interface LoginProps {
  onLoginSuccess: () => void;
}

function Login(props: LoginProps) {
  const { onLoginSuccess } = props;
  const { t: tr } = useTranslation();
  const [nickname, setNickname] = useState<string>('');
  const [logging, setLogging] = useState<boolean>(false);
  const [nickFocus, setNickFocus] = useState<boolean>(false);

  const nickTipClassNames = useMemo(() => {
    const classNames: string[] = [styles['nick-tip']];
    if (nickFocus || nickname) {
      classNames.push('focus');
    }
    return classNames.join(' ');
  }, [nickFocus, nickname]);

  const loginClickHandler = () => {
    const userName = nickname.trim();
    if (logging) {
      return;
    }
    if (!/^[a-zA-Z0-9]+$/.test(userName)) {
      Dialog.alert({
        content: tr('nickname_error'),
        confirmText: tr('confirm'),
      });
      return;
    }
    setLogging(true);

    const userId = userName;
    services.login(userId, userName)
      .then(() => {
        onLoginSuccess();
      })
      .catch((err) => {
        console.log('login fail', err);
        Toast.show({
          icon: 'fail',
          content: tr('login_fail'),
        });
      })
      .finally(() => {
        setLogging(false);
      });
  };

  return (
    <div className={styles['login-page']}>
      <div className={styles['login-form']}>
        <img
          src="https://img.alicdn.com/imgextra/i1/O1CN01i8XGei1UJflU9uYSW_!!6000000002497-2-tps-96-64.png"
          alt="logo"
          className={styles.logo}
        />
        <div className={styles['login-title']}>
          {tr('page_title')}
        </div>
        <div className={styles['nick-block']}>
          <Input
            clearable
            id="aui-interaction-live-nickname"
            autoComplete="off"
            onChange={(value) => setNickname(value)}
            onFocus={() => setNickFocus(true)}
            onBlur={() => setNickFocus(false)}
          />
          <div className={nickTipClassNames}>{tr('nickname_tip')}</div>
        </div>
        <div className={styles['login-btn']}>
          <Button
            disabled={!nickname}
            loading={logging}
            block
            color="primary"
            shape="rounded"
            size="large"
            onClick={loginClickHandler}
          >
            {tr('enter')}
          </Button>
        </div>
      </div>
    </div>
  );
}

export default Login;
